START TRANSACTION;
INSERT INTO updates VALUES ('2021_06_12_135000_create_database.sql');

CREATE DATABASE gade_academy;

CREATE TABLE users(
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(150) NOT NULL,
  `lastname` VARCHAR(150) NOT NULL,
  `password` VARCHAR(255),
  `email` VARCHAR(150) NOT NULL,
  `status` TINYINT(1) NOT NULL DEFAULT 1,
  `created_on` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified_on` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY(id)
);

COMMIT;
